eshop/eshop.Web/Controllers/AccountsController.cs
using eshop.Application;
using eshop.Web.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace eshop.Web.Controllers
{
    public class AccountsController : Controller
    {
        private IUserService userService;

        public AccountsController(IUserService userService)
        {
            this.userService = userService ?? throw new ArgumentNullException(nameof(userService));
        }

        public IActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(UserLoginModel userLoginModel, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var user = userService.ValidateUser(userLoginModel.UserName, userLoginModel.Password);
                if (user != null)
                {
                    Claim[] claims = new Claim[]
                    {
                        new Claim(ClaimTypes.Name, user.UserName),
                        new Claim(ClaimTypes.Email, user.Email),
                        new Claim(ClaimTypes.Role, user.Role),

                    };
                    ClaimsIdentity identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync(claimsPrincipal);

                    if (!string.IsNullOrEmpty(returnUrl) && Url.IsLocalUrl(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }
                    return Redirect("/");
                }
                ModelState.AddModelError("login", "Kullanıcı adı ya da şifre yanlış");
            }
            return View();
        }

        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

eshop/eshop.Web/Controllers/ShoppingCartController.cs
using eshop.Application;
using eshop.Web.Extensions;
using eshop.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace eshop.Web.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IProductService productService;

        public ShoppingCartController(IProductService productService)
        {
            this.productService = productService ?? throw new ArgumentNullException(nameof(productService));
        }

        public IActionResult Index()
        {
            var shoppingCart = getCollectionFromSession();
            return View(shoppingCart);
        }

        public IActionResult AddProduct(int id)
        {
            var product = productService.GetProduct(id);
            if (product != null)
            {
                ShoppingCartCollection cartCollection = getCollectionFromSession();
                cartCollection.AddToCard(product, 1);
                saveToSession(cartCollection);
            }
            return Json(new { message = $"{id} değeri sunucuya ulaştı!" });
        }

        private void saveToSession(ShoppingCartCollection cartCollection)
        {
            //HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(cartCollection));
            HttpContext.Session.SetJson("cart", cartCollection);
        }

        private ShoppingCartCollection getCollectionFromSession()
        {
            //Eğer ilk kez sepete ürün ekleniyorsa;
            //ShoppingCartCollection nesnesini oluştur ve session nesnesine kaydet.
            //Daha önce sepete ürün eklenmiş ise; o zaman session nesnesinden ShoppingCart'ı oku.
            //ShoppingCartCollection shoppingCartCollection = null;
            //if (HttpContext.Session.GetString("cart") == null)
            //{
            //    shoppingCartCollection = new ShoppingCartCollection();
            //    HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(shoppingCartCollection));

            //}

            // string serialized = HttpContext.Session.GetString("cart");
            //Not: Yukarıdaki işlemi; extension metot ile icra ettik... Ayrıntılar için SessionExtensions.cs dosyasına bakınız:
            var registeredShoppingCard = HttpContext.Session.GetJson<ShoppingCartCollection>("cart") ?? new ShoppingCartCollection();

            return registeredShoppingCard;


        }
    }
}

eshop/eshop.Web/ViewComponents/MenuViewComponent.cs
using eshop.Application;
using Microsoft.AspNetCore.Mvc;

namespace eshop.Web.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly ICategoryService _categoryService;

        public MenuViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService ?? throw new ArgumentNullException(nameof(categoryService));
        }

        public IViewComponentResult Invoke()
        {
            var categories = _categoryService.GetCategories();
            return View(categories);
        }
    }
}

eshop/eshop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eshop.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/eshop.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">eshop.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCart" asp-action="Index">Sepetim</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Logout">@User.Identity.Name (Çıkış Yap)</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Login">Giriş Yap</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">

        <main role="main" class="pb-3">
            <div class="row">
                <div class="col-3">
                    @await Component.InvokeAsync("Menu")
                </div>
                <div class="col-9">
                    @RenderBody()
                </div>

            </div>


        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - eshop.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

eshop/eshop.Web/Views/Shared/_productCard.cshtml
@model eshop.Entities.Product

<div class="card">
    <img src="@Model.ImageUrl" class="card-img-top" alt="...">
    <div class="card-body">

        <h5 class="card-title">@Model.Name</h5>
        <p class="card-text">@Model.Price (@Model.Description) </p>
        <!-- <form method="get" asp-action="AddProduct" asp-controller="Cart" asp-route-productId="@Model.Id" asp-route-quantity="1"> -->
            <button  class="btn btn-primary addCart" data-productid="@Model.Id" >Sepete Ekle</button>
        <!-- </form>-->
        <!-- AJAX: Asynchronous JavaScript AND XML -->
    </div>
</div>